### ISSUE TITLE
Cloud Message API (legacy) - question

### ISSUE THREAD

**Issue by Efthymios** [thomasgalliker/Plugin.FirebasePushNotifications#10]
Hi,

Google says that the legacy HTTP or XMPP API will be deprecated on 6/20/2023 and  we must migrate to the latest firebase cloud messaging API (HTTP v1) by 6/20/2024.
My question is this plug in will still working after the 6/20/2024?

Thank you.

**Comment by thomasgalliker** [comment]
Hi. I don't think this will affect the client implementations. Isn't this change related to the Firebase Admin SDK which you use in the backend to send push notifications?

**Comment by Efthymios** [comment]
Hi,

 

Thank you for your reply.

You are right i test it and it works fine.

 

Best Regards,

 

Efthymios Argyrou

I.T. Manager

Alt-àVie Ltd

Mob: +357 99694191

www.altavie.com.cy

altavie-logo

**Comment by thomasgalliker** [comment]
#19
