### ISSUE TITLE
[Bug] MediaPicker.Default.CapturePhotoAsync instant crash linked to FirebasePushNotifications ?

### ISSUE THREAD

**Issue by KaraVehizen** [thomasgalliker/Plugin.FirebasePushNotifications#11]
### Description
I've been using Plugin.FirebasePushNotifications on my android/ios app.
Trying to use Camera to take a photo, the application crashes instantly (even before camera starts), on the MediaPicker.Default.CapturePhotoAsync() call.

The crash occurs in the firebase processintent -> HandleNotificationOpened -> RaiseOrQueueEvent -> Enqueue -> WriteQueueFile
error is Newtonsoft.Json.JsonSerializationException: 'Error getting value from 'Identifier' on 'Android.Content.Intent'.'

(see screenshot)

### Screenshots
![image](https://github.com/thomasgalliker/Plugin.FirebasePushNotifications/assets/164913767/a3f781b5-5e10-4913-932b-f7dd5cd16849)

**Comment by thomasgalliker** [comment]
Very bad. I gonna look at this!

**Comment by thomasgalliker** [comment]
There will be a new pre-release available in a few minutes. Let me know if this solves the problem.
