### ISSUE TITLE
Notification not working on iOS

### ISSUE THREAD

**Issue by REDECODE** [thomasgalliker/Plugin.FirebasePushNotifications#27]
Hello, i use this package as a replacement in the migration process from Xamarin to MAUI and it works on Android but on iOS it doesnt work. Im'm using the version 1.0.26 (the last version not in preview) with net8

After the login process i need to subscribe the user to a topic and i write this code

```
CrossFirebasePushNotification.Current.RegisterForPushNotifications();
CrossFirebasePushNotification.Current.UnsubscribeAll();
CrossFirebasePushNotification.Current.Subscribe("MyTopic");
```

but it crash on the first line RegisterForPushNotifications() with an NullReferenceException. If i force to skip that line, the next two lines are working but if i send a push notification, the real device are not receive it.

**Comment by REDECODE** [comment]
I have an update:

I tried using version.2.51-pre and now the RegisterForPushNotificationsAsync method works, causing the message "do you want to allow notifications" to appear on iOS correctly. However, compiling in release and opening the app after downloading it from TestFlight, it closes with a crash immediately after the splashscreen

**Comment by thomasgalliker** [comment]
Ok. Are you sure the google service file is also present when you do a release build?

**Comment by thomasgalliker** [comment]
Version 1.x is no longer maintained. This was a copy of the previous/Xamarin plugin.

**Comment by REDECODE** [comment]
Thanks for the reply. 
With the last nuget of today now it doesnt crash on release but notification continue to not showing.

I include the GoogleService plist using:

<ItemGroup Condition="$(TargetFramework.Contains('-ios'))">
	<BundleResource Include="Platforms\iOS\GoogleService-Info.plist" Link="GoogleService-Info.plist" />
</ItemGroup>

**Comment by REDECODE** [comment]
Thanks @thomasgalliker for the support! 

As you suggested I made a copy of my app and I try to remove everything from it, just a simple app with a page like in your example. And sending a push notification using the server key and the device token finally it works, but only when app (in debug) are in background. In foreground (in debug) the methods DidReceiveRemoteNotification are not called.
Another problem is that normally i use the topic, and in this new test i made an CrossFirebasePushNotification.Current.SubscribeTopic(topic); but sending a pushnotification from firebase or with my web api that send the notification to firebase nothing are showed when the app is in foregraound nor in background.

**Comment by thomasgalliker** [comment]
I will re-test topics. I think the latest 2.x pre release might has a bug there. Please report if you make progress.

**Comment by REDECODE** [comment]
I try downloading your code, adding the project and ungrading to net8. I found that every step on start and registration works as expected (adding the topic to the queue) but the call DidReceiveRegistrationToken in the FirebasePushNotificationManager.cs is never called. What i could have missing?

Thanks for your help, really apprecieted

**Comment by REDECODE** [comment]
I think is due to Xamarin.Firebase.iOS.CloudMessaging.  
Probably using AdamE.Firebase.iOS.CloudMessaging could solve the issue.

**Comment by REDECODE** [comment]
Sadly changing Xamarin.Firebase.iOS.CloudMessaging to AdamE.Firebase.iOS.CloudMessaging on my fork of your project makes the compilation unbuildable and stuck at Detected signing identity: and not creating the folder Debug\net8.0-ios\ios-arm64

**Comment by thomasgalliker** [comment]
I can re-test on iOS again as soon as I find some time. It is for sure not related to Xamarin.Firebase.iOS.CloudMessaging because this plugin runs in one of our apps and it works there.

**Comment by REDECODE** [comment]
In the end I managed to make everything work, both in the background, foreground and with the topics.

After forking this project I changed Xamarin.Firebase.iOS.CloudMessaging with AdamE.Firebase.iOS.CloudMessaging but having problems with the path resolved by restoring and rebuilding everything via CLI. Then I discovered that the DidReceiveRegistrationToken was never called, in the sense that firebaseMessaging.Delegate was correctly assigned but that this then did not call the callback. However, since the RegisteredForRemoteNotifications was called in the delegate app and if I called the .Token I obtained the fcm token, I forced the RegisteredForRemoteNotifications to call, after assigning the deviceToken to ApnsToken, to call the DidReceiveRegistrationToken which thus goes to pendingTopics. TryDequeue and therefore the SubscribeTopic which otherwise was never called.

**Comment by thomasgalliker** [comment]
Does your AppDelegate look similar to the one provided in the sample app?
https://github.com/thomasgalliker/Plugin.FirebasePushNotifications/blob/0fffdf42ae1930137fc3fe620563d97ea2782d58/Samples/MauiSampleApp/Platforms/iOS/AppDelegate.cs#L25

**Comment by REDECODE** [comment]
Yes except for the exceptions and some try catch the appdelegate is similar to the example.

```
[Register("AppDelegate")]
public class AppDelegate : MauiUIApplicationDelegate
{
    protected override MauiApp CreateMauiApp() => MauiProgram.CreateMauiApp();

    public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
    {            
        return base.FinishedLaunching(application, launchOptions);
    }

    [Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]
    [BindingImpl(BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
    public void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
    {
        try
        {
            CrossFirebasePushNotification.Current.RegisteredForRemoteNotifications(deviceToken);                
            //var token = CrossFirebasePushNotification.Current.Token;
        }
        catch (Exception ex)
        {

        }
    }

    [Export("application:didFailToRegisterForRemoteNotificationsWithError:")]
    [BindingImpl(BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
    public void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
    {
        try
        { 
            CrossFirebasePushNotification.Current.FailedToRegisterForRemoteNotifications(error);
        }
        catch (Exception ex)
        {

        }
    }

    [Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
    public void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
    {
        try
        { 
            CrossFirebasePushNotification.Current.DidReceiveRemoteNotification(userInfo);
            completionHandler(UIBackgroundFetchResult.NewData);
        }
        catch (Exception ex)
        {

        }
    }        
}    
```

The `public void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)` are called correctly and call the  `CrossFirebasePushNotification.Current.RegisteredForRemoteNotifications(deviceToken); `, the problem is that tis function only call `Firebase.CloudMessaging.Messaging.SharedInstance.ApnsToken = deviceToken;` but the `private void DidReceiveRegistrationToken(Firebase.CloudMessaging.Messaging messaging, string fcmToken)` are never called from the delegate, and so the `pendingTopics.TryDequeue` and `SubscribeTopic` are never called

**Comment by thomasgalliker** [comment]
I will have a look at this. Thanks!!

**Comment by WeirdAnakin** [comment]
Is there any update on this? I'm unable to receive FCM messages on iOS and I'm suspecting this issue to be the cause, can you confirm?

**Comment by thomasgalliker** [comment]
I can confirm that FCM push notifications work with the current 2.x pre-release. The question is ‚what does not work and how did you proceed’? In order to clarify this, I‘d recommend to create a new issue or discussion.

**Comment by sovdchains** [comment]
@WeirdAnakin is this related to topics? If so it may be caused by #39

**Comment by WeirdAnakin** [comment]
> I can confirm that FCM push notifications work with the current 2.x pre-release. The question is ‚what does not work and how did you proceed’? In order to clarify this, I‘d recommend to create a new issue or discussion.

In AppDelegate, RegisteredForRemoteNotifications is called and I get a valid token, but DidReceiveRemoteNotification is never called. This is how I initialize (extracted from your MainViewModel sample) and on Android it worked fine from the very beginning:

```
  await this.RequestNotificationPermissionsAsync();
  await this.RegisterForPushNotificationsAsync();

  this.firebasePushNotification.SubscribeTopic("com.mycompany.myapp");

  await this.SubscribeEventsAsync();
```

**Comment by thomasgalliker** [comment]
@REDECODE I applied your fix in RegisteredForRemoteNotifications. If you can test the latest release, I‘d be very happy for any feedback.
