### ISSUE TITLE
[Bug] Exception in Firebase initialization

### ISSUE THREAD

**Issue by fbua** [thomasgalliker/Plugin.FirebasePushNotifications#33]
### Description
Launching the app I got the following exception: 
Java.Lang.IllegalStateException: 'Default FirebaseApp is not initialized in this process it.fbe.TestApp. Make sure to call FirebaseApp.initializeApp(Context) first.'

### Steps to Reproduce

1. Create a new MAUI app
2. Add the nuget package version 2.2.61-pre
3. Edit the project file adding the google-services.json
4. Add the plug-in inizialization UseFirebasePushNotifications with AutoInitEnabled = true

### Expected Behavior
The plug-in will be initialized

### Actual Behavior
An exception occurs

**Comment by thomasgalliker** [comment]
Thanks for taking the time to report this. I gonna look into it.

**Comment by WeirdAnakin** [comment]
Any news on this? I'm hitting the same problem even when I call the InitalizeApp() manually 

`#if ANDROID
                Firebase.FirebaseApp.InitializeApp(Platform.CurrentActivity);
#endif`

**Comment by WeirdAnakin** [comment]
Nevermind, the google-services file wasn't deployed correctly!

**Comment by thomasgalliker** [comment]
What do you mean? The file wasnt in the right place on the phone? Sorry for not being very responsive on this.

**Comment by thomasgalliker** [comment]
Things are boiling hot at the moment. MAUI has a lot of unsolved problem. I hope you bear with me, if it takes some time until bugs are solved 👍🏻

**Comment by thomasgalliker** [comment]
@fbua are you still experiencing this issue with the latest 2.x pre-release?

**Comment by KotM** [comment]
@thomasgalliker I'm experiencing with the same issue. .NET 8, installed 2.3.0-pre version.

I'm just assuming that it can be related to google-services.json setup: I have no GoogleServicesJson build action in the file menu, but I put necessary changes into .csproj as you described before: 

```  <ItemGroup Condition="$(TargetFramework.Contains('-android'))">
    <GoogleServicesJson Include="Platforms\Android\Resources\google-services.json" Link="Platforms\Android\Resources\google-services.json" />
  </ItemGroup>```

Unfortunately it is not working anyway. I'll keep you informed if I will able to resolve the issue.

**Comment by KotM** [comment]
Yep, seems like it was the root of the issue. I have to add the following to my project:

```
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
    <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
      <Version>1.8.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Base">
      <Version>118.5.0.1</Version>
    </PackageReference>
  </ItemGroup>
```

**Xamarin.GooglePlayServices.Base** to make **GoogleServicesJson** working, and **Xamarin.AndroidX.Fragment.Ktx** to make **Xamarin.GooglePlayServices.Base** working. ;)

**Comment by thomasgalliker** [comment]
I cannot reproduce it in my sample app. If you can provide a small public repro app, I can look into it again.

**Comment by KotM** [comment]
https://github.com/KotM/MauiApp_BugDemo

What is interesting, in this project I have **GoogleServicesJson** build action in the menu. But it is not working. :)

**Comment by thomasgalliker** [comment]
info.plist and AndroidManifest.xml don‘t look like they support push notifications.

**Comment by KotM** [comment]
Not sure whether it is the issue. Mentioned AndroidManifest.xml on another project (that was able to start with .UseFirebasePushNotifications() without the exception) almost the same and _notificationPermissions.GetAuthorizationStatusAsync() returns "Denied" for it.

**Comment by AnthonyLatty** [comment]
This issue is still happening with version 2.3.12. Currently I am using version 2.3.5-pre and all is well and I updated to version 2.3.12 and now getting this error.

**Comment by thomasgalliker** [comment]
Can I reproduce the error with this sample app? https://github.com/KotM/MauiApp_BugDemo

**Comment by AnthonyLatty** [comment]
I would like to think so, I used my own project to verify this. What I can say is I started getting this error with the latest release, you can bump the version up in the sample app to test.

**Comment by thomasgalliker** [comment]
I downloaded your [repro app](https://github.com/KotM/MauiApp_BugDemo) and tried to reproduce this issue.
- I added the Android\Resources\google-services.json file from my own demo project
- Then, I added some code to register for push notification, get the token and subscribed to the NotificationReceived event within the MainPage code-behind:

```csharp
   public MainPage()
   {
       InitializeComponent();
   }

   private async void OnCounterClicked(object sender, EventArgs e)
   {
       await IFirebasePushNotification.Current.RegisterForPushNotificationsAsync();
       var token = IFirebasePushNotification.Current.Token;

       IFirebasePushNotification.Current.NotificationReceived += Current_NotificationReceived; ;

   }

   private void Current_NotificationReceived(object? sender, FirebasePushNotificationDataEventArgs e)
   {
   }
```
- After I got the token, I sent following message to it:
```
{
    "message": {
        "token": "{{fcm_token}}",
        "notification": {
            "title": "Notification title",
            "body": "Notification body"
        }
    }
}
```
- Which resulted in hitting the breakpoint in the event handler Current_NotificationReceived:

![MauiApp_BugDemo](https://github.com/user-attachments/assets/6a94ae78-ccca-440c-a992-92cd8bcc478a)

So, I did not experience any errors during the startup process (within UseFirebasePushNotifications).
To proceed with this issue:
- What device/emulator did you use to reproduce this issue? (I used an Android API 34 emulator)
- Can you update your code to the latest pre-release (2.4.x) and let me know if this resolved the issue? (I redesigned the startup process significantly).

**Comment by KotM** [comment]
Hi @thomasgalliker , thank you for your time.

Today, I spent a lot of time attempting to fix this issue. I updated everything and looked into different settings, but still failed.

The final step I took was to just **rebuild** the project and run the debugger again. I rebuilt everything, and it started working. I really like MS products, but I'm not fond of this raw MAUI. :)

**Comment by thomasgalliker** [comment]
Thanks for your response, @KotM. Glad to hear the problem is gone.
I can recommend to use one of the following cleanup scripts if you suffer such issues regulary:
- **clean.bat** on Windows-based developer machines
- **clean.sh** on Linux/macOS-based developer machines

Give Visual Studio or Rider some time after you've run the cleanup script. It requires to build up some cache before you can continuou your work.

**Comment by KotM** [comment]
In my case, the issue was caused by the fact that I had never built the full project before. I had only run it for Android. I think that is the root of the issue: it is necessary to build everything at least once.

**Comment by tsuncp** [comment]
I understand that this issue has been marked as closed. However, I am still experiencing the same problem on both Android and iOS platforms. Could this be related to my use of a multi-project setup for multiple platforms? I have attempted to import the JSON and plist files into both the library project and the platform project. Additionally, I have tried calling UseFirebasePushNotifications in both MauiProgram.cs files.

**Comment by thomasgalliker** [comment]
The problem described in the original question is about`FirebaseApp.initializeApp(Context)` and this method does only exist on Android.

I‘ve never done a multi-project app. If you create a new bug ticket and a small repro app I can look into it 👍🏻
