### ISSUE TITLE
iOS "AndroidFixManifests" parameter is not supported, when run in Release mode 

### ISSUE THREAD

**Issue by VinayendrGada** [thomasgalliker/Plugin.FirebasePushNotifications#36]
### Description
Using .net7.0 and getting error in release mode when trying to build
### Steps to Reproduce

1. Add this package in .net7.0 project
2. Connect to MAC
3. Clean and build in debug it works
4. Select release mode and clean/build Fails

### Expected Behavior
- Build should succeed 

### Actual Behavior
- Failing to build

### Basic Information

- Version with issue: 2.2.68-pre
- Last known good version:

**Comment by thomasgalliker** [comment]
Ok. It might help to install nuget Xamarin.Build.Download in the sample app. I will try it as soon as I have some time available…

**Comment by thomasgalliker** [comment]
It builds on my Windows system with VS and on the MacOS with Rider. Both, Android and iOS. If you provide more infos about the problem I can help.
I recommend you to download the nuget package directly from nuget.org if you don‘t want to poke around in the code 👍🏻
