### ISSUE TITLE
[Bug] After updating 2.2.37-pre package to newest 2.2.69-pre

### ISSUE THREAD

**Issue by MPoels** [thomasgalliker/Plugin.FirebasePushNotifications#37]
After upgrading package from 2.2.37-pre to latest release 2.2.69-pre.

I encountered 2 problems which made me rollback to the 2.2.37 version for production.

On Android (was running fine):
- Notification messages are not removed automatically anymore from the systemtray after processing.
- Data only messages are shown in the message tray (with empty title and body!)

On iOS
No problems.

Just to let you know, and preventing others from searching to why this happens...

Regards, Martien

**Comment by thomasgalliker** [comment]
Can you give me a sample notification json which I can use to reproduce this issue?

**Comment by MPoels** [comment]
Hi Thomas,

Sure, here it is, I altered the token a bit I'm sure this is not critical.
This message gives an empty notification message with the last version, while it should not.

```
{"token":"e3PRXeOlB0xcrCFTZ7CFwF:APA91bE5xya4HuvVeV0aLmbu8PVFL_vqwzzjSVHQ0to7RBCxqcISY-bTNH2neIGZXVuVpM8an9r-Jxihmfptkdt5ZgzrNPM9zwMmufe5NM3V8PUT6v3lcV60iDe5Py1yl9OqQg0WgH96","data":{"event":"StopTransaction","ChargePointId":"ACE0296632"}}
````

**Comment by thomasgalliker** [comment]
You are absolutly right. Data messages display a default notification message - which should not happen!
 I'm working on it. It will take 1-2 days until I can push another release.

**Comment by MPoels** [comment]
Hi Thomas,

No hurry needed the older version does it’s job in production.
Apart from the notification message not displaying correctly, did you also have a look at the issue why after processing the message, the message is not removed from the queue? As this is also a reason why I stayed on the older version.

Regards, Martien

**Comment by thomasgalliker** [comment]
I will have a look at the other issue too. There is a lot of progress in the library right now. I hope some of the issues will be cleared once the next release appears (=planned for tomorrow).

**Comment by MPoels** [comment]
Thanks, all your work is really appreciated, it makes my life a lot easier not having to worry about the uninteresting details of implementing firebase messaging.

Martien

**Comment by thomasgalliker** [comment]
Can you try nuget [2.2.88-pre](https://www.nuget.org/packages/Plugin.FirebasePushNotifications/2.2.88-pre)?
It should no longer show data-only notifications on Android if the app is in background mode.

The queue problem you mentioned sounds new to me. Did you explain it in a separate issue? If not, can you create a new issue for it?

i tested 2.2.88-pre extensivly but I kindly ask you to do so too 👍🏻

**Comment by thomasgalliker** [comment]
There is still something wrong in the latest pre-release on Android. I keep you updated.

**Comment by MPoels** [comment]
Hi Thomas,

Thanks for the update. Sorry I was not able to test it either, as I currently have a deadline on another project...
But I expect to be able to test for you by next week.
Keep up the good work and keep me posted.

Have a nice day.

Martien

**Comment by thomasgalliker** [comment]
I‘m closing this issue for now as I think #30 fixes the mentioned bugs. Let me know if this is true. I can reopen this issue anytime - or we create a new one 👍🏻
