### ISSUE TITLE
New token generate everytime when user login 

### ISSUE THREAD

**Issue by khushal-chothani** [thomasgalliker/Plugin.FirebasePushNotifications#38]
When i login again then new push token is generated
How can i set it to once so it wont be generated
Platform:- Android

**Comment by thomasgalliker** [comment]
I think you cannot configre how/when the tokenis generated. The way I understood is, that you need to send the token to your backend once it is refreshed. You can subscribe to the TokenRefresh event and in the event handler you send the new token to your backend.

**Comment by thomasgalliker** [comment]
Any news on this issue? Did you try my proposal?

**Comment by khushal-chothani** [comment]
Yes before i submit this issue i was doing same.
Sorry for late response.


I'm not sure when the token get refresh like every time we open app then it refresh or any particular duration?
