### ISSUE TITLE
[Enhancement] Include license information

### ISSUE THREAD

**Issue by sovdchains** [thomasgalliker/Plugin.FirebasePushNotifications#40]
## Summary

Currently there is no license info included in this repository and I am uncertain if we can use this library for our use-case.

**Comment by thomasgalliker** [comment]
Thanks for the hint. I just updated the develop branch. I hope MIT license is okay for your use case. I can also offer commercial support if needed.

**Comment by sovdchains** [comment]
Yes this is suitable. Will it also be included in the NuGet package? We currently auto-generate our licenses file based on the NuGet packages data.

**Comment by thomasgalliker** [comment]
Yes, sure, but thanks for the reminder. 

https://www.nuget.org/packages/Plugin.FirebasePushNotifications/2.2.74-pre/License

Let me know if this works for you.

**Comment by sovdchains** [comment]
Yes, works like a charm. Thank you very much!
