### ISSUE TITLE
iOS / .Net 8 - bitcode_strip error 

### ISSUE THREAD

**Issue by jimmich1969** [thomasgalliker/Plugin.FirebasePushNotifications#42]
### Description

When building to a physical device on iOS, I am getting the following error... 
EXEC : error : /Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: missing argument(s) to: -o option [/Users/jmichener/Code/Actabl/MAUI Apps/TranscendentApp (MAUI)/TranscendentApp.csproj::TargetFramework=net8.0-ios]
/Users/jmichener/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/buildTransitive/Xamarin.Firebase.iOS.Core.targets(201,5): error MSB3073: The command "/Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip  -r -o " exited with code 1. [/Users/jmichener/Code/Actabl/MAUI Apps/TranscendentApp (MAUI)/TranscendentApp.csproj::TargetFramework=net8.0-ios]

### Steps to Reproduce

1.  Add nuget Plugin.FirebasePushNotifications v2.2.69-pre
2.  Follow iOS setup instructions
3.  Compile with Target = Physical Device

### Expected Behavior
- No errors

### Actual Behavior
- EXEC : error : /Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: missing argument(s) to: -o option [/Users/jmichener/Code/Actabl/MAUI Apps/TranscendentApp (MAUI)/TranscendentApp.csproj::TargetFramework=net8.0-ios]
/Users/jmichener/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/buildTransitive/Xamarin.Firebase.iOS.Core.targets(201,5): error MSB3073: The command "/Applications/Xcode-15.3.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip  -r -o " exited with code 1. [/Users/jmichener/Code/Actabl/MAUI Apps/TranscendentApp (MAUI)/TranscendentApp.csproj::TargetFramework=net8.0-ios]

### Basic Information

- Version with issue: 2.2.69-pre
- Last known good version: This was the only version I tried so far as I am just adding cloud messaging support to my app

**Comment by thomasgalliker** [comment]
Okay. This sounds not related to this nuget but rather to some wrong build settings.
- Are you able to deploy to the mentioned iOS device if you remove the plugin nuget?
- Do you use the same version of the nuget in all assemblies (if there is more than one).
- Does the sample app build and deploy to the iOS device on your machine?
- Windows with VS2022 or Mac with Rider?

**Comment by thomasgalliker** [comment]
This issue is being closed due to a lack of feedback. It will be reopened if more information is provided.
