### ISSUE TITLE
[Enhancement] Switch to AdamE.Firebase.iOS.CloudMessaging bindings

### ISSUE THREAD

**Issue by codychaplin** [thomasgalliker/Plugin.FirebasePushNotifications#44]
## Summary
`Xamarin.Firebase.iOS.CloudMessaging` is unmaintained and https://github.com/xamarin/GoogleApisForiOSComponents is now archived, meaning it may become unusable in the future. Discussion here: https://github.com/dotnet/maui/discussions/20359

## API Changes
I'm not sure how it works exactly, but this would require swapping out all instances of `Xamarin.Firebase.iOS.CloudMessaging` with `AdamE.Firebase.iOS.CloudMessaging`.

## Intended Use Case
This package may not work on iOS sometime in the future, so this can preemptively prevent that.

**Comment by codychaplin** [comment]
Disregard this, I did not see the earlier issue about the same topic.

**Comment by thomasgalliker** [comment]
Yep, it's in the pipeline. So far, the old bindings still seem to work fine.
