### ISSUE TITLE
[Bug] [iOS] Cannot resolve symbol in AppDelegate

### ISSUE THREAD

**Issue by palatinb** [thomasgalliker/Plugin.FirebasePushNotifications#49]
#### Description
We upgraded the package from 2.2.91-pre to 2.2.117 version and after that in the Platforms/iOS/AppDelegate we get an error for the `RegisteredForRemoteNotifications` and `FailedToRegisterForRemoteNotifications`.

The error in Rider is the following: Cannot resolve symbol 

#### Steps to Reproduce

1. 
2. 
3. 

#### Expected Behavior
- 

#### Actual Behavior
- 

#### Basic Information

- Version with issue: 2.2.117
- Last known good version: 2.2.91-pre

#### Screenshots

![Képernyőfotó 2024-08-14 - 17 14 47](https://github.com/user-attachments/assets/0211c286-afa4-4700-bada-f3dbaa6cb2e4)

**Comment by thomasgalliker** [comment]
I was having this issue too! Damn. Let me think how I solved it. The methods are there, they‘re not missing.

**Comment by thomasgalliker** [comment]
I think it has to do with MAUI workloads and/or your Rider version. When you update from the older to the newer version, Rider does not reference the iOS-specific dll to your iOS-project. Instead, the iOS-part of your project „sees“ the netstandard dll. This cost me more than a day to figure out whats going on. 
Try run a full workload update: `dotnet worload update`. Then check if they are all still there `dotnet workload list`. If not, reinstall the workloads.

**Comment by thomasgalliker** [comment]
Very strange. I wonder if other nugets cause the same problem or if I misconfigured something…

**Comment by thomasgalliker** [comment]
[FAQ.md updated](https://github.com/thomasgalliker/Plugin.FirebasePushNotifications/blob/develop/Docs/FAQ.md#where-have-the-platform-specific-methods-gone)
