### ISSUE TITLE
[Bug] NullReferenceException at Plugin.FirebasePushNotifications.Platforms.FirebasePushNotificationManagerBase.set_NotificationCategories(NotificationCategory[] value)

### ISSUE THREAD

**Issue by NGumby** [thomasgalliker/Plugin.FirebasePushNotifications#55]
#### Description
When calling RegisterNotificationCategories too early, you get a NullReferenceException

#### Steps to Reproduce

In my MainPage constructor, I call this code :

           CrossFirebasePushNotification.Current.TokenRefreshed += OnTokenRefresh;
           CrossFirebasePushNotification.Current.NotificationOpened += OnNotificationOpenedAsync;
           CrossFirebasePushNotification.Current.NotificationReceived += OnNotificationReceivedAsync;
           CrossFirebasePushNotification.Current.NotificationDeleted += OnNotificationDeletedAsync;
           CrossFirebasePushNotification.Current.NotificationAction += OnNotificationActionAsync;

           var notificationCategories = new NotificationCategory[]
              {
                   new NotificationCategory("dismiss",new NotificationAction[] {
                       new NotificationAction("Dismiss","Dismiss", NotificationActionType.Default),
                   }),
                   new NotificationCategory("navigate",new NotificationAction[] {
                       new NotificationAction("Dismiss","Dismiss", NotificationActionType.Default),
                       new NotificationAction("Navigate","Navigate To", NotificationActionType.Foreground)
                   })
           };
           CrossFirebasePushNotification.Current.RegisterNotificationCategories(notificationCategories);

#### Expected Behavior
- 

#### Actual Behavior
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Plugin.FirebasePushNotifications.Platforms.FirebasePushNotificationManagerBase.set_NotificationCategories(NotificationCategory[] value)
   at Plugin.FirebasePushNotifications.Platforms.FirebasePushNotificationManagerBase.RegisterNotificationCategories(NotificationCategory[] notificationCategories)

#### Basic Information

- Version with issue: 2.3.12
- Last known good version: never

**Comment by thomasgalliker** [comment]
Not cool. I try to reproduce it tomorrow 👍🏻 Thanks for reporting.

**Comment by NGumby** [comment]
Forgot to say that it works if I do that later in the pipeline.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thomasgalliker** [comment]
This issue involves a refactoring in the initialization process of the library. Not very easy stuff. I started working on a new branch but it will take some days to release a test version of the nuget.

**Comment by thomasgalliker** [comment]
@NGumby can you try with the latest 2.4.x pre-release nuget?

**Comment by NGumby** [comment]
I have tried it and it's fixed!  Thanks again!
