### ISSUE TITLE
[Bug] Missing privacy manifest for iOS

### ISSUE THREAD

**Issue by sgreifeneder** [thomasgalliker/Plugin.FirebasePushNotifications#58]
#### Description

Got the following message when submitting an app for review in App Store Connect:

> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/FBLPromises.framework/FBLPromises”, which includes FBLPromises, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements. 

For the following SDKs:
- FBLPromises
- FirebaseCore
- FirebaseCoreDiagnostics
- FirebaseInstallations
- FirebaseMessaging
- GoogleDataTransport

#### Steps to Reproduce

1. Include Plugin.FirebasePushNotifications in a MAUI app
2. Build and publish iOS app
3. Send app to review

#### Expected Behavior
- privacy manifest exists, I don't get a warning during app review and I can also submit app updates after November 12th 2024

#### Actual Behavior
- privacy manifest missing

#### Basic Information

- Version with issue: 2.3.12
- Last known good version: n/a

**Comment by thomasgalliker** [comment]
I think that‘s something you have to add to the app that is using this library.

**Comment by sgreifeneder** [comment]
We already have a privacy manifest for our app (I think you can't submit anymore without it). 
But in this case, the SDK/library provider has to include a privacy manifest as well. 

Apple is also explicitly mentioning that: 
> Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest.

See also
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
https://developer.apple.com/support/third-party-SDK-requirements

**Comment by thomasgalliker** [comment]
Strangly, I cannot see this ITMS-91061 warnings in our solution. Do you get it when you upload the ipa file with Transporter.app? How can I reproduce this issue? - As far as I read on github, we need to place a privacy file in this library. I didn't know that.

**Comment by sgreifeneder** [comment]
I'm uploading the ipa file from a GitHub Action: `apple-actions/upload-testflight-build`
But in the logs I can see that there are no errors (I also don't get any notification from Apple about it). 

Only when I submit the build for review, I get a mail with the above mentioned warnings.

**Comment by sgreifeneder** [comment]
Hi @thomasgalliker, any update here?

**Comment by thomasgalliker** [comment]
No update yet in this direction. There is currently a lot of other priority work going on.
- Is the warning you receive a show stopper - or does Apple still accept the app?
- If you have the time to do some research on what exactly we have to update here, I'd highly appreciate it. Merge requests are welcome!

**Comment by sgreifeneder** [comment]
I don't know what your priority work is, but according to the Apple message, no one would be able to submit new apps or app updates using your Firebase PN SDK starting Nov 12th (which is in 2 months):
> Starting November 12, 2024, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK **must** include a privacy manifest file.

As of now, Apple is still accepting the app, but I think this should be high prio.

**Comment by thomasgalliker** [comment]
Work performed for paying customers = priority work. You can fork this repo, add all privacy info needed to comply with Apple, create a merge request and I‘ll review it with high priority.

**Comment by thomasgalliker** [comment]
Newer versions of [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk) contain the necessary privacy manifest files (PrivacyInfo.xcprivacy). Therefore we need to resolve #19 first and get this issue resolved _for free_.

**Comment by sgreifeneder** [comment]
Ok, can you already estimate when the work on this can be started or how long it would take?

**Comment by thomasgalliker** [comment]
@sgreifeneder 
Do you like to test the latest version 3.0.x? It contains the firebase ios sdk 10.27.

**Comment by sgreifeneder** [comment]
Hi @thomasgalliker, thanks for the update, will try next week.

**Comment by sgreifeneder** [comment]
iOS push notifications worked for me, both foreground (prio high) and background. To verify the privacy manifest, I actually need to submit the app for review - unfortunately you don't get the issue when you just upload a binary to testflight.
But as of now, 3.0.x is just a pre version. When are you planning to release a production 3.0.x?

**Comment by thomasgalliker** [comment]
True. 3.0.x is actually ready to be release for production. I could not find any problems with the latest 3.0.x pre-release. I'll create a stable 3.0.x release (maybe today). If the new iOS firebase bindings don't solve your problem, we're going to create another branch. I'll keep you updated.

**Comment by sgreifeneder** [comment]
Thanks. 
Is there a reason you went for firebase ios sdk version v10.27.0 and not a higher one? Latest one would be v11.3.0, and latest v10 version is v10.29.0

**Comment by thomasgalliker** [comment]
I basically just replaced Xamarin.Firebase.iOS.CloudMessaging with AdamE.Firebase.iOS.CloudMessaging in the iOS part of the library. Good question why AdamE.Firebase.iOS.CloudMessaging is not using the 11.x bindings. I can imagine its a tough work to keep these bindings updated. I‘m already happy to have v10.x tbh.

**Comment by AlleSchonWeg** [comment]
I published last week our iOS app to the App Store without problems. The app is still a Xamarin Forms app with the old CrossGeeks library. I have no privacy manifest in this app.

**Comment by thomasgalliker** [comment]
Ok, but I guess you took this [nuget](https://dev.azure.com/CrossGeeks/Plugins/_build/results?buildId=1029&view=artifacts&pathAsName=false&type=publishedArtifacts) with the updated version 10.x bindings for your Xamarin app?

**Comment by thomasgalliker** [comment]
PR #74 is planned to contain the replacement of the Firebase iOS binding for MAUI. It will take some more days until I can release it.

**Comment by AlleSchonWeg** [comment]
> Ok, but I guess you took this [nuget](https://dev.azure.com/CrossGeeks/Plugins/_build/results?buildId=1029&view=artifacts&pathAsName=false&type=publishedArtifacts) with the updated version 10.x bindings for your Xamarin app?

No. The original nuget: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.4.35

**Comment by sgreifeneder** [comment]
@thomasgalliker since Nov 12th is approaching: do you already know, when a stable 3.x version will be released?

**Comment by thomasgalliker** [comment]
Cool, thank you very much for your feedback!

**Comment by Nandulucky** [comment]
Hello @thomasgalliker,

Thanks for the update.

I was previously using the following packages in my project:

Plugin.FirebasePushNotifications: Version 2.5.13
Xamarin.Firebase.iOS.Analytics: Version 8.10.0.1
After updating Plugin.FirebasePushNotifications from version 2.5.13 to 3.0.17, I started encountering the following build error:

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net8.0_18.0/18.0.8314/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_APMAnalyticsConfiguration", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[x86_64][10](FIRAnalytics.o)
  "_APMAppMeasurementOriginFirebase", referenced from:
      +[FIRAnalytics startWithConfiguration:options:] in FirebaseAnalytics[x86_64][10](FIRAnalytics.o)
  (and more errors related to FirebaseAnalytics...)`
  
  It seems to be related to Firebase Analytics. Could you please suggest the following:

How can I resolve this issue?
Which NuGet package is recommended for Firebase Analytics compatibility with the latest Plugin.FirebasePushNotifications version?
Thank you in advance for your help.

**Comment by thomasgalliker** [comment]
@Nandulucky I would recommend you create a new issue from this error. Also describe what OS and IDE you use in the new issue. Its easier for the community if we tackle small problems in small issies 🙏
