### ISSUE TITLE
[Bug] Notifications only launch the app if the application is not in the background (killed) instead of displaying them

### ISSUE THREAD

**Issue by dylix** [thomasgalliker/Plugin.FirebasePushNotifications#6]
Notifications only launch the app if the application is not in the background (killed) instead of displaying them.
If the app is in the background, I will have a page popup that shows the contents of the notification, this works when the app is in the background and foreground. However if the app is not running, only the app is launched and nothing is displayed

It's a bit hard to debug for me, since I cant see what's going on with a closed app, perhaps you have some insight going on here.

I am using the refactoring/cleanup branch, however I believe the same issue would be on the normal branch as well

### Expected Behavior
- Open app, display notification

### Actual Behavior
- Only launches app

**Comment by thomasgalliker** [comment]
@dylix 
Which version of the nuget package are you using? Did you subscribe to the notification events? Is there any code you can share so I can help you with troubleshooting?
