### ISSUE TITLE
[Enhancement] Push notification for iOS do not generate notification sound

### ISSUE THREAD

**Issue by eyeveye** [thomasgalliker/Plugin.FirebasePushNotifications#60]
#### Summary
When receiving a push notification for iOS, it didn't generate any notification sound.

### Intended 
When receiving a push notification for iOS, it should have an alert sound.

**Comment by eyeveye** [comment]
Sound = "default" would generate the alert sound.

**Comment by luisrr1590** [comment]
I'm having this issue.

Where are you setting that Sound = "default"?

I have a NotificationDelegate in which I set:

UNMutableNotificationContent notificationContent = new UNMutableNotificationContent();
notificationContent.Title = title;
notificationContent.Body = body;
notificationContent.Sound = UNNotificationSound.Default;

This, however, does not work.
