### ISSUE TITLE
Installation on visual studio 2022: path too long

### ISSUE THREAD

**Issue by DavideSigma** [thomasgalliker/Plugin.FirebasePushNotifications#61]
Try to install the package from Nuget Gallery but I got an error due to the long path of some file. Enabling LongPath in Windows doesn't solve the problem

**Comment by thomasgalliker** [comment]
Did you see this #31? It seems like this is an issue on Windows 11 and Visual Studio.

Please let me know if you have any idea how I have to change the code in this repository to have this issue solved.

I work on Windows 10 with VS and MacOS with Rider. Both combinations work smoothly.

**Comment by thomasgalliker** [comment]
@DavideSigma I think this is is a valueable source of information: https://github.com/AdamEssenmacher/GoogleApisForiOSComponents?tab=readme-ov-file#long-path-issue-root-cause

**Comment by thomasgalliker** [comment]
I updated the [FAQ.md](https://github.com/thomasgalliker/Plugin.FirebasePushNotifications/blob/develop/Docs/FAQ.md#long-path-issue-on-windows-11) in this repository. Since this issue is not directly related to the source code of this repository, I'm going to close this issue.
