### ISSUE TITLE
Document/allow user to use INotificationPermissions without dependency injection

### ISSUE THREAD

**Issue by vchelaru** [thomasgalliker/Plugin.FirebasePushNotifications#62]
#### Summary
The main documentation explains how to obtain an instance of IFirebasePushNotification using Current (I realize it's not the recommended pattern) without using dependency injection. However, the documentation does not explain how to get an INotificationPermissions without using dependency injection. I would expect to also have a .Current property or to obtain it in a similar way. Is this supported? If so, updating the main page docs to explain this would be helpful.

#### API Changes
No api changes, unless an INotificationPermissions.Current property is added.

#### Intended Use Case
This use case is for users who are not using dependency injection but would like to use the library.

**Comment by vchelaru** [comment]
Understood, and for reference I'm using the service locator pattern with interfaces, so I just need the static instance to inject it into my own service locator. Also, for quick-n-dirty tests or evaluation of the library this could be a nice addition.

**Comment by thomasgalliker** [comment]
I have added `INotificationPermissions.Current`. Wasn't a big change, so, I added this change into another set of changes that soon will be released.

**Comment by thomasgalliker** [comment]
You can try the [latest nuget pre-release](https://www.nuget.org/packages/Plugin.FirebasePushNotifications/2.4.9-pre) and let me know if this help.
