### ISSUE TITLE
Does not work for .Net 8

### ISSUE THREAD

**Issue by cissemy** [thomasgalliker/Plugin.FirebasePushNotifications#7]
Getting the error :
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/data/app/~~araqHuso6EOt8i74qmMOrQ==/cissemy.deluxedirect-JupaUInlxZGfJs1RqZjSSg==/base.apk"],nativeLibraryDirectories=[/data/app/~~araqHuso6EOt8i74qmMOrQ==/cissemy.deluxedirect-JupaUInlxZGfJs1RqZjSSg==/lib/arm64, /data/app/~~araqHuso6EOt8i74qmMOrQ==/cissemy.deluxedirect-JupaUInlxZGfJs1RqZjSSg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]

**Comment by thomasgalliker** [comment]
Can you check the latest nuget pre-release https://www.nuget.org/packages/Plugin.FirebasePushNotifications/2.2.2-pre and let me know if it works under .net 8?
