### ISSUE TITLE
[Enhancement] UNNotificationPresentationOptions for iOS

### ISSUE THREAD

**Issue by banditoth** [thomasgalliker/Plugin.FirebasePushNotifications#71]
#### Summary
The CrossGeeks nuget have option to set the UNNotificationPresentationOptions on iOS. This version is not supporting it yet.

```csharp
FirebasePushNotificationManager.ShouldShowWhen = UNNotificationPresentationOptions.Alert;
```

#### API Changes
I would propose to do it like custom options on Android on the apphostbuilder extension method.

```csharp
            .UseFirebasePushNotifications(options =>
            {
                //options.AutoInitEnabled = false;
                options.AutoInitEnabled = true;
#if IOS
                options.iOS.PresentationOptions = UNNotificationPresentationOptions.Alert;
#endif
#if ANDROID
                options.Android.NotificationActivityType = typeof(MainActivity);
                options.Android.NotificationChannels  = new Plugin.FirebasePushNotifications.Platforms.Channels.NotificationChannelRequest[]
                {
                    new Plugin.FirebasePushNotifications.Platforms.Channels.NotificationChannelRequest()
                    {
                        ChannelId = "default_channel_id",
                        ChannelName = "Default Channel",
                        Description = "The default notification channel",
                        LockscreenVisibility =  Android.App.NotificationVisibility.Public,
                        Importance = Android.App.NotificationImportance.High,
                        IsDefault = true,
                    }
                };
#endif
``` -->

**Comment by thomasgalliker** [comment]
Looks like a cool idea.

**Comment by thomasgalliker** [comment]
@banditoth can I ask you for a favor? Can you read issue #70 and leave a comment in issue 70 if you also experience the same problem. I'm not 100% sure if issue 70 is really an iOS 18 problem - or a problem of this library.

**Comment by banditoth** [comment]
> @banditoth can I ask you for a favor? Can you read issue #70 and leave a comment in issue 70 if you also experience the same problem. I'm not 100% sure if issue 70 is really an iOS 18 problem - or a problem of this library.

Unfortunately, I'm unable to start my iOS project, since I'm having issues that the code runs magically somehow on iOS to CrossFirebasePushNotification.cs's line of: `throw Exceptions.NotImplementedInReferenceAssembly();`

**Comment by thomasgalliker** [comment]
Are you using Rider? Rider has the very unfortunate issue that, when you install a nuget that is built for an iOS sdk you dont have the worloads installed for, it references the net8.0 assembly to your iOS project instead of the net8.0-ios. Check the referenced assemblies.

Which .NET version do you use? Which xcode version?

**Comment by banditoth** [comment]
> Are you using Rider? Rider has the very unfortunate issue that, when you install a nuget that is built for an iOS sdk you dont have the worloads installed for, it references the net8.0 assembly to your iOS project instead of the net8.0-ios. Check the referenced assemblies.
> 
> Which .NET version do you use? Which xcode version? What version of the nuget did cause this issue?
> 
> What could help is a repair or update of the workloads.

The issue was related to outdated dotnet workloads, and xcode version. After upgrading to macOS Seq, XCode 16, and the 8.0.4xx version of .NET SDK solved the issue.

Other: We already conencted on linkedin, but for history, I'm writing the conclusions of our discussion on the tests:
On iOS 18 with Plugin.FirebasePushNotifications older version of 2.5.x gives the duplicate notification receive. Newer versions seems to solve this issue.

**Comment by thomasgalliker** [comment]
So, if the idea of `PresentationOptions` would be, to override the default presentation option, given by the `priority` data?

- If a notification is received which has no priority data - or - the priority is below high, then the PresentationOptions are consulted.
- Affects only iOS notifications. 
- Affects only notifications shown while app runs in foreground.

Correct me if I‘m wrong or unclear, @banditoth

**Comment by thomasgalliker** [comment]
@banditoth can you check version 2.5.15-pre
You can now set `options.iOS.PresentationOptions = UNNotificationPresentationOptions.Banner;` to add `Banner` to the persentation options (in case it's not already added by the priority flag).

I'm just asking myself what the use case of this change is? Someone doesn't want to use the priority flag but generally want to say 'Always display the banner if the app is in foreground mode'?

Another question: This `PresentationOptions` only add flags. What if we also could remove flags? Someone could send a message with priority=high which adds `List and Banner` by default but doesn't want to `List` the notification in the notification center, etc...
