### ISSUE TITLE
[Bug] in version 3.0.17 getting 'Could not copy  C:\N\adame.firebase.ios.core\10.29.0.1' error

### ISSUE THREAD

**Issue by Th3L0x** [thomasgalliker/Plugin.FirebasePushNotifications#90]
#### Description
On windows when deploying to Android  device (release mode) I getting a series of this and like this warnings in the build console

Could not copy C:\N\adame.firebase.ios.core\10.29.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface

Also when I try to update via Nuget Package Manager I get similar error

Could not find a part of the path 'C:\N\adame.firebase.ios.core\10.29.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.				

I tried to delete bin/obj, delete nuget packages then 'dotnet restore'

The  long path limit is disabled, my nuget,temp and project folders are all in the root of C:/

I reverted the package version to 2.5.35 and now its working fine like before the update.

Workload versions:
maccatalyst                18.0.8303/8.0.100      VS 17.11.35327.3
android                    34.0.113/8.0.100       VS 17.11.35327.3
ios                        18.0.8303/8.0.100      VS 17.11.35327.3
aspire                     8.1.0/8.0.100          VS 17.11.35327.3
maui-windows               8.0.82/8.0.100         VS 17.11.35327.3

#### Steps to Reproduce
Update to 3.0.17 and try to deploy to Android device

#### Expected Behavior
- Build done, Deploy done

#### Actual Behavior
- Build failed

#### Basic Information
- Version with issue: 3.0.17 
- Last known good version:  2.5.35

**Comment by thomasgalliker** [comment]
Strange, because the replacement of the firebase ios sdk, which is the major change in version 3.0.x, should not have any influence on the Android side.
- Does the error also occur if you‘re connected to the mac build host?
- Is your app using .NET 7 or 8?
- Which MauiVersion do you use?

**Comment by Th3L0x** [comment]
- On Mac I can update to 3.0.17, but on startup the app throws an initalization error (from a different package? I'm using admob too)

Loaded assembly: /private/var/containers/Bundle/Application/4C0C72EC-A844-4DC0-BC07-57C407C885EC/Maui.app/hu/Maui.resources.dll [External]
2024-11-09 20:05:25.572 Maui[3411:699026] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without AppMeasurement. Google AdMob publishers, follow instructions here: https://googlemobileadssdk.page.link/admob-ios-update-plist to include the AppMeasurement framework and set the -ObjC linker flag. Google Ad Manager publishers, follow instructions here: https://googlemobileadssdk.page.link/ad-manager-ios-update-plist'
*** First throw call stack:
(0x1a9a6540c 0x1a2d41c28 0x1a9bbee8c 0x1003c1608 0x100370ecc 0x1b080b7a8 0x1b080c780 0x1b07e39f8 0x1b07f0c68 0x1b07f1430 0x1f480ab94 0x1f480a720)

- When I revert the package to 2.5.35 everything works fine on Mac/iOS too
- On windows I checked the update again via package manager console and ran this command:

Install-Package Plugin.FirebasePushNotifications
Got this error:
  NotFound https://nuget.pkg.github.com/Th3L0x/download/adame.firebase.ios.core/index.json 295ms
  OK https://nuget.devexpress.com/api/FindPackagesById()?id='AdamE.Firebase.iOS.Core'&semVerLevel=2.0.0 719ms
Install-Package : Could not find a part of the path 'C:\N\adame.firebase.ios.core\10.29.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_
64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.

- Poject version: .NET 8
- MAUI version: maui 8.0.82/8.0.100  SDK 8.0.400

**Comment by Th3L0x** [comment]
Do you have any news or progress on this?

**Comment by thomasgalliker** [comment]
No news right now. I'm working on a Macos with Jetbrains Rider as IDE at the moment. I can try to install the nuget on a Windows pc, but it will take time until I can do so. The one thing I can clearly say about this issue is, that it is probably the Firebase iOS SDK (Nuget adame.firebase.ios.core) that causes the troubles. If you have a proposal on how to change the code in this repository to make it work, let me know. Unfortunately, I cannot change code inside adame.firebase.ios.core or how MAUI bindings are used/compiled.

**Comment by Th3L0x** [comment]
Okay, so the problem is with the AdamEssenmacher/GoogleApisForiOSComponents package 
(adame.firebase.ios.core)
This is a bug or something like that in the VisualStudio (Windows) itself, it can not handle a long path issue no matter where you set the nuget packeg or temp folder or the main project path.

I call these command in powershell

```
dotnet nuget locals all -c # Clear all Nuget cache
cd $env:localappdata # Go to your AppData\Local folder
Get-ChildItem -Filter "*Xamarin*" # Check for your XamarinBuildDownloadCache folder
rm -Force -Recurse XamarinBuildDownloadCache # Delete that folder
Get-ChildItem -Filter "*Xamarin*" # Confirm that it has been deleted
```
then from cmd run
dotnet restore
dotnet build

From cmd I can build debug version, release version, deploy to device, publish.
From VisualStudio only the debug version can be built, but at least I can debug the code from Windows.
So i had to write some powershell script to automate the deploy/publish procces until someone fix this.

This iOS error on Mac

Loaded assembly: /private/var/containers/Bundle/Application/4C0C72EC-A844-4DC0-BC07-57C407C885EC/Maui.app/hu/Maui.resources.dll [External]

was solved by adding this key to the Info.plist:

```
<key>GADIsAdManagerApp</key>
<true/>
```

**Comment by thomasgalliker** [comment]
Thanks for taking the time and documenting the solution!
