### ISSUE TITLE
Version 3.0.17 Path too long installing nuget

### ISSUE THREAD

**Issue by giaza** [thomasgalliker/Plugin.FirebasePushNotifications#91]
I am using VS 17.11.5. with net 8. I get this error trying to install the nuget package. I even tried to move the project folder into the root of the hard disk, the error stays.

System.IO.PathTooLongException: Path or file name too long. Complete file name must be less than 260 characters, while the directory name must be less than  248 characters.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   in System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   in NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   in NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   in NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   in NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()

**Comment by thomasgalliker** [comment]
This is something we cannot solve here. It's an issue cause by Windows 11 and/or Visual Studio.
#31 and #61 already asked the same question. Have a look at those closed issues how they managed to solve it. Sorry for no better news.

**Comment by giaza** [comment]
I see, thank you for your help.
